<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>CodeBrix.SSH.Tests</AssemblyName>
    <RootNamespace>CodeBrix.SSH.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="SilverAssertions.ApacheLicenseForever" Version="1.0.164.180" />
    <PackageReference Include="CodeBrix.TestMocks.ApacheLicenseForever" Version="1.0.165.1173" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CodeBrix.SSH\CodeBrix.SSH.csproj" />
  </ItemGroup>

</Project>
